language: python
sudo: false

python: "3.6"
node_js: "8"

cache:
  pip: true

install:
  - pip install -r requirements.txt

script:
  - ./build.sh

deploy:
 repo: sequelize/sequelize.github.io
 target_branch: master
 provider: pages
 skip_cleanup: true
 github_token: $GH_TOKEN
 local_dir: site
 on:
   branch: master